# 0x From the Ubuntu terminal color palette

# 0x Default colors
[colors.primary]
background = '#222222'
foreground = '#D0CFCC'

# 0x Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = 'CellBackground'
cursor = 'CellForeground'

# 0x Normal colors
[colors.normal]
black   = '#171421'
red     = '#C01C28'
green   = '#26A269'
yellow  = '#A2734C'
blue    = '#12488B'
magenta = '#A347BA'
cyan    = '#2AA1B3'
white   = '#D0CFCC'

# 0x Bright colors
[colors.bright]
black   = '#5E5C64'
red     = '#F66151'
green   = '#33DA7A'
yellow  = '#E9AD0C'
blue    = '#2A7BDE'
magenta = '#C061CB'
cyan    = '#33C7DE'
white   = '#FFFFFF'
